apiVersion: apps/v1
kind: Deployment
metadata:
  name: oilwise-ai-engine
  namespace: oilwise
  labels:
    app: oilwise-ai-engine
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: oilwise-ai-engine
  template:
    metadata:
      labels:
        app: oilwise-ai-engine
    spec:
      containers:
      - name: ai-engine
        image: oilwise-ai-engine:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: AI_ENGINE_PORT
        - name: BACKEND_URL
          value: "http://oilwise-backend:3000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: oilwise-ai-engine
  namespace: oilwise
  labels:
    app: oilwise-ai-engine
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: oilwise-ai-engine

