apiVersion: apps/v1
kind: Deployment
metadata:
  name: oilwise-backend
  namespace: oilwise
  labels:
    app: oilwise-backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: oilwise-backend
  template:
    metadata:
      labels:
        app: oilwise-backend
    spec:
      containers:
      - name: backend
        image: oilwise-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: oilwise-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oilwise-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: oilwise-secrets
              key: JWT_SECRET
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: REDIS_URL
        - name: MQTT_BROKER
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: MQTT_BROKER
        - name: AI_ENGINE_URL
          valueFrom:
            configMapKeyRef:
              name: oilwise-config
              key: AI_ENGINE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: oilwise-backend
  namespace: oilwise
  labels:
    app: oilwise-backend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: oilwise-backend

