apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oilwise-ingress
  namespace: oilwise
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.oilwise.in
    - ai.oilwise.in
    secretName: oilwise-tls
  rules:
  - host: api.oilwise.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oilwise-backend
            port:
              number: 3000
  - host: ai.oilwise.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oilwise-ai-engine
            port:
              number: 5000
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@oilwise.in
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

